from enum import StrEnum
from typing import Literal

Currency = Literal["USD", "EUR"]


class OrderFailureStep(StrEnum):
    RESERVE_INVENTORY = "RESERVE_INVENTORY"
    CAPTURE_PAYMENT = "CAPTURE_PAYMENT"
    FINALIZE_INVENTORY_SALE = "FINALIZE_INVENTORY_SALE"
    CREATE_INVOICE = "CREATE_INVOICE"
    SEND_NOTIFICATION = "SEND_NOTIFICATION"


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class WorkerProcessResultOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    NO_WORK = "NO_WORK"
    STALE_QUEUE_DISCARDED = "STALE_QUEUE_DISCARDED"
